# Generated by Django 4.0.2 on 2022-02-15 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='resumen',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='tipo',
            field=models.CharField(choices=[('n', 'Noticias'), ('a', 'Archivos')], default='n', max_length=1),
            preserve_default=False,
        ),
    ]
