# Generated by Django 4.1.1 on 2022-09-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_publicacion_creado_publicacion_modificado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(upload_to='archivos/%Y-%m-%d-%H/'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='tipos',
            field=models.ManyToManyField(to='noticias.tipo'),
        ),
    ]
