# Generated by Django 4.1.1 on 2022-09-19 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_tipo_alter_archivo_archivo_publicacion_tipos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='tipos',
        ),
    ]
