# Generated by Django 4.1.1 on 2022-09-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_remove_publicacion_tipo_publicacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='prioridad',
            field=models.FloatField(default=1),
        ),
    ]
