# Generated by Django 4.1.1 on 2022-09-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_tipo_prioridad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo',
            options={'ordering': ['prioridad', 'id']},
        ),
    ]
