# Generated by Django 4.1.1 on 2022-09-20 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0008_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='noticias.departamento'),
            preserve_default=False,
        ),
    ]
