# Generated by Django 4.1.1 on 2022-09-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0009_tipo_departamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['prioridad', 'id']},
        ),
        migrations.AddField(
            model_name='departamento',
            name='prioridad',
            field=models.FloatField(default=1),
        ),
    ]
