# Generated by Django 4.1.1 on 2022-09-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0010_alter_departamento_options_departamento_prioridad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoridades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('cargo', models.CharField(max_length=500)),
                ('prioridad', models.FloatField(default=1)),
            ],
            options={
                'ordering': ['prioridad', 'id'],
            },
        ),
    ]
