# Generated by Django 4.1.1 on 2022-10-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0011_autoridades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(upload_to='archivos/%Y-%m-%d-%H-%i-%s-%u/'),
        ),
    ]
