# Generated by Django 4.1.1 on 2022-10-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0012_alter_archivo_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='prioridad',
            field=models.FloatField(default=1),
        ),
    ]
