# Generated by Django 5.0.1 on 2024-01-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0013_archivo_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='destacar',
            field=models.BooleanField(default=False),
        ),
    ]
