# Generated by Django 4.0.2 on 2022-02-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('users', 'Permiso al modulo de usuarios'), ('noticias', 'Permiso al modulo de noticias')),
            },
        ),
    ]
