# Generated by Django 4.0.2 on 2022-02-21 14:34

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension, CITextExtension

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
        CITextExtension()
    ]
